### ISSUE TITLE
Fine tune on custom dataset

### ISSUE THREAD

**Issue by rafikg** [memray/OpenNMT-kpg-release#47]
Hi @memray 
Is there any readme or notebook to fine-tune the model on custom dataset?

**Comment by memray** [comment]
Please stay tuned as we are preparing for a tutorial at ECIR. A new [codebase](https://github.com/midas-research/dlkp) will be released and it can support fine-tuning better. It supports more pretrained models and datasets. New checkpoints will be released as well. Appreciate your patience!

Rui

**Comment by ahadda5** [comment]
Dear Rui,  any updates on this. 

- Many notebooks rely on  /data/keyphrase  which does not exit in the latest master branch
- Would love to see such a demo to fine tune  models on our own data?

Regards!

**Comment by memray** [comment]
Hi @rafikg and @ahadda5 , I uploaded datasets I used for training at [huggingface](https://huggingface.co/datasets/memray/keyphrase/tree/main). Following the same json format and config files [here](https://github.com/memray/OpenNMT-kpg-release/tree/master/script/transfer/train_fulldata), you would be able to train models with your own data. Notebook is not a good way for training since it doesn't work well with multiple GPUs.
