### ISSUE TITLE
About Transformer performance

### ISSUE THREAD

**Issue by LeaLiLu** [memray/OpenNMT-kpg-release#8]
Hi Memray, 
Thanks for sharing the source code ! It's really helpful !
I'd like to know that whether you have tried Transformer ? And how about the performance of Transformer with copy mechanism ?

**Comment by memray** [comment]
Hi LeaLiLu,

Yes I've tried. I don't see clear signs that Transformers outperform RNNs on this task for now. You can take a look at this [paper](https://arxiv.org/abs/1909.03590) for reference, which provides some Transformers' results (note that the scores may not be directly comparable to other studies because the F@5/@10 is computed a little differently). We are still working on determining the reason. Discussions and contributions are welcome!

Rui
